services:
  - type: web
    name: portfolio-api
    runtime: docker
    dockerfilePath: ./portfolio-api/Dockerfile
    dockerContext: ./portfolio-api
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
